version: "3.8"

services:
  backend:
    build:
      context: ./IntelligentDocumentAnalysisAPI
    ports:
      - 10010:80
    environment:
      - DOTNET_ENVIRONMENT=Development
    depends_on:
      - database
  database:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@123
    ports:
      - 1433:1433
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
